version: '3.8'

#https://docs.docker.com/compose/compose-file/compose-file-v3/#compose-and-docker-compatibility-matrix

name: dabtest

services: 
  singlewebapplication.api:
    image: ${DOCKER_REGISTRY-}singlewebapplicationapi
    build:
      context: .
      dockerfile: ./SingleWebApplication.API/Dockerfile
  singlewebapplication.dataapibuilder:
    image: ${DOCKER_REGISTRY-}singlewebapplicationdataapibuilder
    build: 
      context: .
      dockerfile: ./SingleWebApplication.DataAPIBuilder/Dockerfile
      args:
        - DAB_CONFIG=/SingleWebApplication/swa-db-connections/staticwebapp.database.config.json
    environment:
      - DATABASE_CONNECTION_STRING= /run/secrets/database_connection_string
      #- DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
    secrets:
      - database_connection_string   
    ports:
      - 5033:5000
  singlewebapplication:
    image: ${DOCKER_REGISTRY-}singlewebapplication
    build:
      context: .
      dockerfile: ./SingleWebApplication/Dockerfile 

secrets: 
  database_connection_string:          
    environment: "DATABASE_CONNECTION_STRING"
    

    
    
        


  
    
  