version: '3.8'

#https://docs.docker.com/compose/compose-file/compose-file-v3/#compose-and-docker-compatibility-matrix

name: dabtest

services: 
  singlewebapplication:
    image: swacli/static-web-apps-cli:1.1.7
    ports:
      - 4280:4280
    volumes:
      - ./SingleWebApplication:/app/SingleWebApplication
    working_dir: /app/SingleWebApplication
    command: swa start http://localhost:5000 --run "dotnet watch run"
    depends_on:
      - singlewebapplication.dataapibuilder
  singlewebapplication.dataapibuilder:
    image: ${DOCKER_REGISTRY-}singlewebapplicationdataapibuilder
    build: 
      context: .
      dockerfile: ./SingleWebApplication.DataAPIBuilder/Dockerfile
      args:
        - DAB_CONFIG=/SingleWebApplication/swa-db-connections-container/staticwebapp.database.config.json
    environment:
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
    ports:
      - 5033:5000
  singlewebapplication.api:
    image: ${DOCKER_REGISTRY-}singlewebapplicationapi
    build:
      context: .
      dockerfile: ./SingleWebApplication.API/Dockerfile