version: '3.8'

#https://docs.docker.com/compose/compose-file/compose-file-v3/#compose-and-docker-compatibility-matrix

name: dabtest

services: 
  singlewebapplication:
    image: ${DOCKER_REGISTRY-}singlewebapplication
    build: 
      context: .
      dockerfile: ./SingleWebApplication/Dockerfile
    ports:
      - 4280:4280
      - 5274:5000
    environment:
      - MS_VS_CONTAINERS_TOOLS_LOGGING_ENABLED=true
      - MS_VS_DOCKER_TOOLS_LOGGING_ENABLED=true
      - PYTHONUNBUFFERED=1 
      - SWA_CLI_DEBUG=silly
      - DEBUG=true      
    depends_on:
      - singlewebapplication.dataapibuilder
  singlewebapplication.dataapibuilder:
    image: ${DOCKER_REGISTRY-}singlewebapplicationdataapibuilder
    build: 
      context: .
      dockerfile: ./SingleWebApplication.DataAPIBuilder/Dockerfile
      args:
        - DAB_CONFIG=/SingleWebApplication/swa-db-connections-container/staticwebapp.database.config.json
    environment:
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
    ports:
      - 5033:5000
  singlewebapplication.api:
    image: ${DOCKER_REGISTRY-}singlewebapplicationapi
    build:
      context: .
      dockerfile: ./SingleWebApplication.API/Dockerfile