name: Data API Builder, Docker Image to Container Apps

on:  
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RESEARCHDATAAPIBUILDERDAB_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/SingleWebApplication.DataAPIBuilder 
          registryUrl: defaultwrutkowski.azurecr.io
          registryUsername: ${{ secrets.RESEARCHDATAAPIBUILDERDAB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RESEARCHDATAAPIBUILDERDAB_REGISTRY_PASSWORD }}
          containerAppName: research-data-api-builder-dab
          resourceGroup: research-data-api-builder
          imageToBuild: defaultwrutkowski.azurecr.io/research-data-api-builder-dab:${{ github.sha }}
          buildArguments: |
            "DAB_CONFIG=${{ vars.DAB_CONFIG }}" 
          
            

     

